services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: chirag
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: image_classification
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always  

  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always  
    
volumes:
  postgres_data:
